### ISSUE TITLE
Script Not Working

### ISSUE THREAD

**Issue by vinayakbaranwal12** [tactu2023/cPanel-nulled#1]
I hope this email finds you well. I am writing to seek assistance with an issue I encountered while using the cPanel repository (https://github.com/tactu2023/cPanel-nulledl). I am currently running cPanel version 98, and after applying the code from the repository, I am unable to log back into the server.

Here are the details of the problem I encountered:

1. **Version:** I am using cPanel version 98.

2. **Issue:** After applying the code from the repository mentioned above, I encountered difficulties logging back into the server.The error for Unlimited license is still there.

3. **Steps Taken:** I followed the instructions provided in the repository and applied the code accordingly. However, after the changes were implemented, I found myself unable to access the server.

4. **Error Message:** When attempting to log in, I received the following error message [if applicable, provide the specific error message you encountered].

I kindly request your assistance in resolving this matter as soon as possible.Your prompt attention to this matter is greatly appreciated.

**Comment by tactu2023** [comment]
In the current version, the cpanel license only works on VPS servers sold by us.
The system detects this and stops if it is not a server offered by us
We are working on a version to offer nulled cPanel licenses on external servers

**Comment by vinayakbaranwal12** [comment]
Can i get a expected date for the external release for the servers?
That will be appreciated very much..

**Comment by tactu2023** [comment]
check :
https://github.com/tactu2023/cPanel-nulled/blob/main/README.md#cpanel-nulled-external-vps

**Comment by vinayakbaranwal12** [comment]
The service is trial for a period of 15 days. It expires before date 23/10/2023_-_06:24. Please renew the service before this time to avoid stopping it.
You will receive notifications a few days before the series expires.


Do i need to get a new openvpn everytime??

If possible, ps. share more details on this

**Comment by tactu2023** [comment]
The license works only through the VPN tunnel. If you don't want to go through a VPN tunnel, then I can offer you a VPS server from our network.
view : https://github.com/tactu2023/cPanel-nulled/blob/main/README.md#cpanel-nulled-internal-vps

**Comment by vinayakbaranwal12** [comment]
The Thing i am asking is that it had a notification saying that the vpn is at 15 Days
The service is trial for a period of 15 days. It expires before date 23/10/2023_-_06:24. Please renew the service before this time to avoid stopping it.
You will receive notifications a few days before the series expires.

do i need to buy the VPN service after 15 days again?

**Comment by tactu2023** [comment]
You will receive these details by email. The system sends these notifications automatically!
ask more details here : 
https://t.me/+EZd22NEl74k4YWY8 or https://chat.whatsapp.com/DUVTzNwKDo9AHSAALxEZgI
