### ISSUE TITLE
Error : 404

### ISSUE THREAD

**Issue by bladhac** [tactu2023/cpanel-nulled#1]
Your server is not eligible to use our cpanel license!
Error : 404

**Comment by tactu2023** [comment]
The generated error (404) is not from our script, are you sure you are using the current script?

**Comment by bladhac** [comment]
Yes, I'm sure I used the same codes as yours and followed the instructions

**Comment by bladhac** [comment]
any reply?

**Comment by tactu2023** [comment]
We have released a new version.
